pipeline:
  publish-docker:
    image: plugins/docker
    repo: ilyazzz/foobot2
    tags:
      - latest
    secrets:
      - source: DOCKER_USERNAME
        target: plugin_username
      - source: DOCKER_PASSWORD
        target: plugin_password