pipeline:
  publish-docker:
    image: docker
    commands:
      - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - docker build -t docker.io/ilyazzz/foobot2 .
      - docker push docker.io/ilyazzz/foobot2
    secrets: [ DOCKER_USERNAME, DOCKER_PASSWORD ]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock