pipeline:
  publish-docker:
    image: docker
    commands:
      - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
      - docker build -t docker.io/ilyazzz/foobot2 .
      - docker push docker.io/ilyazzz/foobot2
    secrets: [ DOCKER_USERNAME, DOCKER_PASSWORD ]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock