pipeline:
  build-push:
    image: docker
    commands:
      - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
      - docker build -t docker.io/ilyazzz/foobot2 .
      - docker push docker.io/ilyazzz/foobot2
    secrets: [ DOCKER_USERNAME, DOCKER_PASSWORD ]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
        
  deploy:
    image: appleboy/drone-ssh
    host:
      from_secret: ssh_host
    username:
      from_secret: ssh_user
    port:
      from_secret: ssh_port
    key:
      from_secret: ssh_key
    script:
      - cd $DEPLOY_PATH
      - docker compose pull
      - docker compose up -d
