pipeline:
  pull-repo:
    image: appleboy/drone-ssh
    host: ${SSH_HOST}
    port: 22
    key_path: /root/.ssh/id_rsa
    secrets: [ ssh_host, ssh_username, repo_dir ]
    volumes:
      - /root/.ssh/id_rsa:/root/.ssh/id_rsa
    script:
      - cd /media/big/volumes/foobot/src
      - git pull --no-rebase

branches: master
