pipeline:
  build-push:
    image: docker
    commands:
      - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
      - docker build --build-arg=SCCACHE_MEMCACHED="$SCCACHE_MEMCACHED" -t git.hyron.dev/foobot/foobot2
      - docker push ghcr.io/foobot/foobot2
    secrets: [ DOCKER_USERNAME, DOCKER_PASSWORD, SCCACHE_MEMCACHED ]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
        
  deploy-swarm:
    image: docker:latest
    volumes:
      - /run/docker.sock:/run/docker.sock
    commands:
      - ocker service update --image git.hyron.dev/foobot/foobot2 foobot_foobot

branches: master
