pipeline:
  build-push:
    image: docker
    commands:
      - echo $DOCKER_PASSWORD | docker login git.hyron.dev -u $DOCKER_USERNAME --password-stdin
      - docker build --build-arg=SCCACHE_MEMCACHED="$SCCACHE_MEMCACHED" -t git.hyron.dev/foobot/foobot2 .
      - docker push git.hyron.dev/foobot/foobot2
    secrets: [ DOCKER_USERNAME, DOCKER_PASSWORD, SCCACHE_MEMCACHED ]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
        
  #deploy-swarm:
  #  image: docker:latest
  #  volumes:
  #    - /run/docker.sock:/run/docker.sock
  #  commands:
  #    - docker service update --image git.hyron.dev/foobot/foobot2 foobot_foobot

branches: master
