pipeline:
  publish-docker:
    image: plugins/docker
    repo: ilyazzz/foobot2
    tags:
      - latest
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
