pipeline:
  build-push:
    image: docker
    commands:
      - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
      - docker build -t docker.io/ilyazzz/foobot2 .
      - docker push docker.io/ilyazzz/foobot2
    secrets: [ DOCKER_USERNAME, DOCKER_PASSWORD ]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
        
  deploy:
    image: appleboy/drone-ssh
    host: ${SSH_HOST}
    port: 22
    key_path: /root/.ssh/id_rsa
    secrets: [ ssh_host, ssh_username ]
    volumes:
      - /root/.ssh/id_rsa:/root/.ssh/id_rsa
    script:
      - cd ~/docker/foobot/
      - docker compose pull
      - docker compose up -d

branches: master
