[package]
name = "foobot2"
version = "0.10.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15.0"

diesel = { git = "https://github.com/diesel-rs/diesel.git", features = [
    "mysql",
    "r2d2",
    "serde_json",
] }
diesel_migrations = { git = "https://github.com/diesel-rs/diesel.git" }

tokio = { version = "1.17.0", features = ["full"] }
futures = "0.3.21"
async-trait = "0.1.53"
#async-recursion = "0.3"

tracing = "0.1.34"
tracing-subscriber = "0.3.11"

reqwest = { version = "0.11.10", default-features = false, features = [
    "json",
    "rustls-tls",
] }
http = "0.2.6"

serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"

twitch-irc = { version = "4.0.0", default-features = false, features = [
    "transport-tcp-rustls-webpki-roots",
    "refreshing-token-rustls-webpki-roots",
] }
twilight-http = "0.10.2"
twilight-model = "0.10.2"
twilight-gateway = "0.10.1"
twilight-cache-inmemory = "0.10.2"
twilight-util = { version = "0.10.1", features = ["permission-calculator"] }

frankenstein = { version = "0.13.0", default-features = false, features = [
    "async-http-client",
] }

minecraft-client-rs = "0.1.0"

handlebars = "4.2.2"

rocket = { version = "0.5.0-rc.1", features = ["secrets"] }
rocket_okapi = { version = "0.8.0-rc.1", features = ["rapidoc"] }
passwords = "3.1.9"

anyhow = "1.0.56"
thiserror = "1.0.30"

rand = "0.8.5"

hmac = "0.12.1"
sha2 = "0.10.2"
hex = "0.4.3"

dashmap = "5.2.0"

chrono = "0.4.19"

irc = { version = "0.15.0", default-features = false, features = [
    "tls-rust",
    "ctcp",
    "toml_config",
] }

prometheus = { version = "0.13.0", features = ["process"] }
rocket_prometheus = "0.10.0-rc.1"
once_cell = "1.10.0"

rhai = { version = "1.6.1", features = ["sync", "serde"] }

tonic = { version = "0.7.1", features = ["tls", "compression"] }
prost = "0.10.1"

regex = "1.5.5"

[build-dependencies]
tonic-build = { version = "0.7.0", features = ["prost", "compression"] }
