[package]
name = "foobot2"
version = "0.9.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15"

diesel = { git = "https://github.com/diesel-rs/diesel.git", features = ["mysql", "r2d2", "serde_json"] }
diesel_migrations = { git = "https://github.com/diesel-rs/diesel.git" }

tokio = { version = "1.6", features = ["full"] }
futures = "0.3"
async-trait = "0.1"
#async-recursion = "0.3"

tracing = "0.1"
tracing-subscriber = "0.3"

reqwest = { version = "0.11", default-features = false, features = ["json", "rustls-tls"] }
http = "0.2"

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

twitch-irc = { git = "https://github.com/robotty/twitch-irc-rs", default-features=false, features = ["transport-tcp-rustls-webpki-roots", "refreshing-token"] }
twilight-http = "0.9"
twilight-model = "0.9"
twilight-gateway = "0.9"
twilight-cache-inmemory = "0.9"
twilight-util = { version = "0.9", features = ["permission-calculator"] }

handlebars = "4.1"

rocket = { version = "0.5.0-rc.1", features = ["secrets"] }
rocket_dyn_templates = { version = "0.1.0-rc.1", features = ["handlebars"] }

passwords = "3.1"

anyhow = "1.0"
thiserror = "1.0"

rand = "0.8"

hmac = "0.12"
sha2 = "0.10"
hex = "0.4"

dashmap = "5.0"

chrono = "0.4"

irc = "0.15"
