[package]
name = "foobot2"
version = "0.10.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15"

diesel = { git = "https://github.com/diesel-rs/diesel.git", features = ["mysql", "r2d2", "serde_json"] }
diesel_migrations = { git = "https://github.com/diesel-rs/diesel.git" }

tokio = { version = "1.17", features = ["full"] }
futures = "0.3"
async-trait = "0.1"
#async-recursion = "0.3"

tracing = "0.1"
tracing-subscriber = "0.3"

reqwest = { version = "0.11", default-features = false, features = ["json", "rustls-tls"] }
http = "0.2"

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

twitch-irc = { version = "4.0", default-features=false, features = ["transport-tcp-rustls-webpki-roots", "refreshing-token-rustls-webpki-roots"] }
twilight-http = "0.9"
twilight-model = "0.9"
twilight-gateway = "0.9"
twilight-cache-inmemory = "0.9"
twilight-util = { version = "0.9", features = ["permission-calculator"] }

frankenstein = { version = "0.10", default-features = false, features = ["async-http-client"] }

minecraft-client-rs = "0.1"

handlebars = "4.1"

rocket = { version = "0.5.0-rc.1", features = ["secrets"] }
rocket_okapi = { version = "0.8.0-rc.1", features = ["rapidoc"] }
passwords = "3.1"

anyhow = "1.0"
thiserror = "1.0"

rand = "0.8"

hmac = "0.12"
sha2 = "0.10"
hex = "0.4"

dashmap = "5.1"

chrono = "0.4"

irc = { version = "0.15", default-features = false, features = ["tls-rust", "ctcp", "toml_config"] }

prometheus = { version = "0.13", features = ["process"] }
rocket_prometheus = "0.10.0-rc.1"
once_cell = "1.9"

rhai = { version = "1.5", features = ["sync", "serde"] }

tonic = { version = "0.6", features = ["tls", "compression"] }
prost = "0.9"

regex = "1.5"

[build-dependencies]
tonic-build = { version = "0.6", features = ["prost", "compression"] }