version: "3"

services:
  db:
    image: docker.io/mariadb
    environment:
      MARIADB_USER: foobot
      MARIADB_PASSWORD: foobot
      MARIADB_RANDOM_ROOT_PASSWORD: "true"
      MARIADB_DATABASE: "foobot"
    volumes:
      - db:/var/lib/mysql
    ports:
      - 3306:3306
  nats:
    image: nats
    ports:
      - 4222:4222 

  jaeger:
    image: quay.io/jaegertracing/all-in-one:latest    
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - 16686:16686
      - 4317:4317
      - 4318:4318

volumes:
  db:
